In [1]:
import numpy as np
from PIL import Image

In [7]:
b = np.zeros((3,5))
print(b)
print('len:',len(b))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
len: 3


### 函数装饰器--带参数形式

In [23]:
def foo(fn):
    def bar(*args, **kwargs):
        fn(*args, **kwargs)
        print("*" * 15)
    return bar

@foo
def my_test(a):
    print("my_test function", a)

@foo
def my_test2(a, b):
    print("my_test2 function", a, "", b)

my_test(4)
my_test2(6, 8)

my_test function 4
***************
my_test2 function 6  8
***************


### Gauss-Seidel 迭代法

In [38]:
import numpy as np

def Gauss(a, b, m):
    n = len(a)
    p = np.zeros((n, 1), dtype = np.double)
    d = 10 ** (-9)
    max2 = 0
    x = np.zeros((n, 1), dtype = np.double)
    for i in range(m):
        for j in range(n):
            if j == 0:
                x[0] = (b[0] - a[0, 1:].dot(p[1:]))/a[0, 0]
            elif j == n-1:
                x[n-1] = (b[n-1] - a[n-1, :n-1].dot(x[:n-1]))/a[n-1, n-1]
            else:
                x[j] = (b[j] - a[j, :j].dot(x[:j])-a[j, j+1:].dot(p[j+1:])) / a[j, j]
        err = np.max(np.abs(x - p))
        relerr = err / (np.max(np.abs(x)) + d)
        p = x.copy()
        if err < d or relerr < d:
            break
    return max2, x

print("未知数个数:")
n = int(input())
print("系数矩阵 A")
a = np.zeros((n, n), dtype = np.double)
for r in range(n):
    a[r, :] = np.array(input().split(), dtype = np.double)
print("指数矩阵 B")
b = np.zeros((n,1))
for r in range(n):
    b[r] = np.array(input(), dtype = np.double)
print("最大循环次数 m：")
m = int(input())
max2, x=Gauss(a, b, m)
print("循环次数：", m)
print("Gauss迭代近似解：",x)

未知数个数:
3
系数矩阵 A
3 2 -1
1 3 2
2 -1 3
指数矩阵 B
6
9
3
最大循环次数 m：
10
循环次数： 10
Gauss迭代近似解： [[0.99775409]
 [1.99640303]
 [1.00029828]]


### Jacobi 迭代法

In [39]:
import numpy as np

def Gauss(a, b, m):
    n = len(a)
    p = np.zeros((n, 1), dtype = np.double)
    d = 10 ** (-9)
    max2 = 0
    x = np.zeros((n, 1), dtype = np.double)
    for i in range(m):
        for j in range(n):
                x[j] = (b[j] - a[j, :].dot(p) + a[j, j] * (p[j])) / a[j, j]
        err = np.max(np.abs(x - p))
        relerr = err / (np.max(np.abs(x)) + d)
        p = x.copy()
        if err < d or relerr < d:
            break
    return max2, x

print("未知数个数:")
n = int(input())
print("系数矩阵 A")
a = np.zeros((n, n), dtype = np.double)
for r in range(n):
    a[r, :] = np.array(input().split(), dtype = np.double)
print("指数矩阵 B")
b = np.zeros((n,1))
for r in range(n):
    b[r] = np.array(input(), dtype = np.double)
print("最大循环次数 m：")
m = int(input())
max2, x=Gauss(a, b, m)
print("循环次数：", m)
print("Gauss迭代近似解：",x)

未知数个数:
3
系数矩阵 A
3 2 -1
1 3 2
2 -1 3
指数矩阵 B
6
9
3
最大循环次数 m：
10
循环次数： 10
Gauss迭代近似解： [[1.00889092]
 [1.96855154]
 [1.00741757]]
