### Numpy操作学习

In [3]:
import numpy as np

### 列表转化为矩阵

In [24]:
a = [[1,2,3],[2,3,4]]
array = np.array(a)
print('list:',a,'\n array:', array)

list: [[1, 2, 3], [2, 3, 4]] 
 array: [[1 2 3]
 [2 3 4]]


### 查看numpy的属性

In [25]:
print('number of dim:',array.ndim) #维度
print('shape:',array.shape)#各维度数量
print('size:',array.size)#元素总个数

number of dim: 2
shape: (2, 3)
size: 6


### 指定数据

In [ ]:
a = np.array([2,23,4],dtype=np.int)#类似的可指定为int64、int32、float64、float32
print(a.dtype)

### 创建特殊矩阵

In [ ]:
#全零,三行四列
a = np.zeros((3,4)) 
print(a,'\n')

#全一,三行四列，且指定为int32
a = np.ones((4,4,5), dtype = np.int32)
a = a[0:2,1:3].reshape(-1,3)
print(a,'\n')

#空矩阵，值接近于零
a = np.empty((3,4))
print(a,'\n')

#用arange创建连续数组
a = np.arange(1,10,2)
print(a, '\n')

#用linspace创建线段性数据,0-20分割成10个线段
a = np.linspace(0,20,10)
print(a)



### Numpy的基础操作_1

In [ ]:
#用reshape改变数据形状
a = np.arange(12).reshape((-1,3))#一般reshape((row,column)),若为((-1,column))则行数由系统判定
print(a, '\n')

#基本加减法
a = np.array([[1,2,3],[2,3,4]])
b = np.linspace(1,20,6).reshape((2,3))

c = a + b
d = a - b
e = a * b
f = a ** 2
print(a,'\n\n',b,'\n')
print('sum:',c,'\n\n','sub:',d,'\n\n','product',e,'\n\n','pow',f)


### Numpy的基础操作_3

In [ ]:
#调用三角函数
a = np.linspace(1,10,6).reshape((2,3))
b = 10 * np.sin(a)
print(b)

#逻辑判断
c = b < 3
print(c)

#标准矩阵乘法
c = np.dot(a,b.reshape((-1,2))) #或者a.dot(b),这里b矩阵要变形以满足矩阵乘法规则
print(c)

#创建随机数组成的矩阵
a = np.random.random((2,4))
print(a)
print()

#求和值、最小值、最大值,axis=1为行，0为列
print('sum:', np.sum(a)) #numpy.sum asix=null时加和所有元素
print('max:', np.max(a,axis=1))
print('min:', np.min(a,axis=0)) 

### Numpy的基础操作_3

In [ ]:
#指定精度
a = np.random.random((3,2))
a = np.around(a,decimals = 4)
print(a,'\n')

#argmin()、argmax()求矩阵最小、大值索引
print('index of min:{0}\t, index of max:{1}'.format(a.argmin(), a.argmax()))

#求均值mean()或average()
print('mean:%.4f'%np.mean(a))

#中位数
print('median:%.4f'%np.median(a))

#累加元素
print('cumsum:\n',np.cumsum(a))

#累差元素
print('diff:\n',np.diff(a))
print()

#检查所有非零元素的位置，并重构成两个矩阵
a = np.array([[0, 10, 5],[2, 0, 1]])
print(a)
print(np.nonzero(a))

#排序
print('sort:\n',np.sort(a))

#转置
print('transpose:\n',np.transpose(a)) #或者a.T

#替换，将小于指定最小值或指定大于最大值的元素替换为最小值或最大值
print('clip:\n',np.clip(a,1,9))

### Numpy 索引

In [ ]:
#一维
a = np.arange(1,11)
print(a)
print(a[1])


a = a.reshape((2,5))
print(a)
print(a[1])

#二维
print(a[1][1]) #a[1][1] == a[1,1]
print(a[1, 1:4])

#逐行访问
print('row:')
for row in a:
    print(row)
    
#逐列访问
print('column:')
for c in a.T:
    print(c)
    
#访问所有元素
#method.1
print('all_1:',end='\t')
for i in a.flat:
    print(i,end=' ')
    
print()

#method_2
print('all_2:',end='\t')
for r in a:
    for i in r:
        print(i,end=' ')

### Numpy array合并与分割

In [43]:
a = np.ones((1, 3))
b = np.zeros((2, 3))
print("数据")
print(a)
print("-"*25)
print(b)
print("*"*25)


print('纵向合并(同列数)')
print(np.vstack((a, b)))

print()

print('横向合并（同行数）')
c =b.reshape((1, 6))
print(np.hstack((a, c)))
print()

#多矩阵合并
print("合并")
d = np.concatenate((a, b, a), axis=0)
print(d,'\n')
e = np.concatenate((a, c, a), axis=1)
print(e)

#纵向分割
print(np.split(e, 3, axis =1))

#横向分割
print(np.split(d, 2, axis = 0))

#不等量分割
print(np.array_split(d, 2, axis=1))

数据
[[1. 1. 1.]]
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
*************************
纵向合并(同列数)
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

横向合并（同行数）
[[1. 1. 1. 0. 0. 0. 0. 0. 0.]]

合并
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]] 

[[1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]
[array([[1., 1., 1., 0.]]), array([[0., 0., 0., 0.]]), array([[0., 1., 1., 1.]])]
[array([[1., 1., 1.],
       [0., 0., 0.]]), array([[0., 0., 0.],
       [1., 1., 1.]])]
[array([[1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.]]), array([[1.],
       [0.],
       [0.],
       [1.]])]


### Numpy copy

In [ ]:
a = np.ones((3,3))

c = a
d = c

a[1 ,2]=5

print(d)
print(c is a)#判断c与a是否相同

d[2, 1]=3
print(a)

#若用copy()的方式赋值，则无关联性
b = a.copy()
a[1, 1] = 3
print(b is a)


### 插入

In [36]:
a = np.ones((3, 3))

a = np.insert(a, np.shape(a)[1], 2, axis = 1)

print(a)

[[1. 1. 1. 2.]
 [1. 1. 1. 2.]
 [1. 1. 1. 2.]]
